In [13]:
import gym
import pandas
import numpy

In [2]:
print(gym)

<module 'gym' from '/home/lars/DRL_AI4RoMoCo/code/environment/gym/gym/__init__.py'>


In [3]:
env = gym.make("Ur10Heg-v7")

/home/lars/DRL_AI4RoMoCo/code/environment/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [4]:
env.sim.data.get_body_xpos("gripper_dummy_heg")

array([ 0.57243453, -0.83605904,  1.17575472])

In [5]:
env.sim.data.get_body_xmat("gripper_dummy_heg")

array([[-1.00000000e+00,  6.35274710e-22,  3.67320510e-06],
       [ 3.67320510e-06,  3.33066907e-16,  1.00000000e+00],
       [-6.35274710e-22,  1.00000000e+00, -3.33066907e-16]])

In [15]:
positions = []
vector = numpy.array([6,6,6])

In [17]:
for i in range(10):
    positions.append(numpy.concatenate([env.sim.data.get_body_xpos("gripper_dummy_heg"), vector]))

In [18]:
positions

[array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ]),
 array([ 0.57243453, -0.83605904,  1.17575472,  6.        ,  6.        ,
         6.        ])]

In [19]:
pos_df = pandas.DataFrame(positions)

In [20]:
pos_df

0         1         2    3    4    5
0  0.572435 -0.836059  1.175755  6.0  6.0  6.0
1  0.572435 -0.836059  1.175755  6.0  6.0  6.0
2  0.572435 -0.836059  1.175755  6.0  6.0  6.0
3  0.572435 -0.836059  1.175755  6.0  6.0  6.0
4  0.572435 -0.836059  1.175755  6.0  6.0  6.0
5  0.572435 -0.836059  1.175755  6.0  6.0  6.0
6  0.572435 -0.836059  1.175755  6.0  6.0  6.0
7  0.572435 -0.836059  1.175755  6.0  6.0  6.0
8  0.572435 -0.836059  1.175755  6.0  6.0  6.0
9  0.572435 -0.836059  1.175755  6.0  6.0  6.0